{{- define "base-library.namespace" -}}
{{- if .Values.namespace.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "base-library.fullname" . }}
  {{- if .Values.namespace.labels }}
  labels:
    {{- toYaml .Values.namespace.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.namespace.annotations }}
  annotations:
    {{- toYaml .Values.namespace.annotations | nindent 4 }}
  {{- end }}
spec: {}
Status: {}
{{- end -}}
{{- end -}}