{{- define "base-library.secrets" -}}
{{- if .Values.application.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "base-library.fullname" . }}-secret
  labels:
    {{- include "base-library.labels" . | nindent 4 }}
    {{- with .Values.application.secrets.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "base-library.annotations" . | nindent 4 }}
    {{- with .Values.application.secrets.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
{{ toYaml .Values.application.secrets.data | nindent 2 }}
---
{{- end }}
{{- end }}