apiVersion: v2
name: app-archetype
description: A Helm Chart for a generic application archetype
version: 0.0.1
dependencies:
  - name: base-library
    version: 0.0.1
    # repository: "file://../base-library"